export const institutionName12={
    "tenantId": "kl.cochin",
    "moduleName": "egov-location",
    "institutionList": [
      {
        "code": "INSTITUTION_2404",
        "institutionName": "Harbour Policestation",
        "institutionNamelocal": "ഹാര്‍ബര്‍ പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2404,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 1,
        "street": "Bristo Road",
        "place": "Railway Station Road",
        "wardId": 25,
        "poId": 20,
        "streetLocal": "ബ്രിസ്റ്റോ റോഡ്",
        "placeLocal": "റെയിവേ സ്റ്റേഷന്‍ റോഡ്",
        "buildingNo": 1936,
        "buildingName": "Harbour Policestation",
        "buildingNameLocal": "ഹാര്‍ബര്‍ പോലീസ് സ്റ്റേഷന്‍",
        "phoneNo": "04/09/99",
        "phoneDesig": 36,
        "mainPlace": "Willington Island",
        "mainPlaceLocal": "വില്ലിംഗ്ടണ്‍ ഐലന്‍റ്",
        "registar": [
          {
            "institutionRegistar": "M K Vijayan",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_SUB_INSPECTOR_OF_POLICE"
          }
        ],
        "active": true,
        "address": "Harbour Policestation,Bristo Road,Railway Station Road",
        "addressLocal": "ഹാര്‍ബര്‍ പോലീസ് സ്റ്റേഷന്‍,ബ്രിസ്റ്റോ റോഡ്,റെയിവേ സ്റ്റേഷന്‍ റോഡ്",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2405",
        "institutionName": "Mattanchery Police Station",
        "institutionNamelocal": "മട്ടാഞ്ചേരി പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2405,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 3,
        "street": "Mattanchery ",
        "place": "Mattanchery ",
        "wardId": 6,
        "poId": 11,
        "streetLocal": "മട്ടാഞ്ചേരി",
        "placeLocal": "മട്ടാഞ്ചേരി",
        "buildingNo": "NULL",
        "buildingName": "Mattanchery Police Station",
        "buildingNameLocal": "മട്ടാഞ്ചേരി പോലീസ് സ്റ്റേഷന്‍",
        "phoneNo": "4/13/7989",
        "phoneDesig": 36,
        "mainPlace": "Mattanchery ",
        "mainPlaceLocal": "മട്ടാഞ്ചേരി",
        "registar": [
          {
            "institutionRegistar": "A M Jose",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_SUB_INSPECTOR_OF_POLICE"
          }
        ],
        "active": true,
        "address": "Mattanchery Police Station,Mattanchery ,Mattanchery ",
        "addressLocal": "മട്ടാഞ്ചേരി പോലീസ് സ്റ്റേഷന്‍,മട്ടാഞ്ചേരി,മട്ടാഞ്ചേരി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2406",
        "institutionName": "Vanitha Police Station",
        "institutionNamelocal": "വനിതാ പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2406,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 4,
        "street": "E R G Road",
        "place": "Kompara",
        "wardId": 40,
        "poId": 19,
        "streetLocal": "ഇ ആര്‍ ജി റോഡ്",
        "placeLocal": "കോംപാറ",
        "buildingNo": 3490,
        "buildingName": "Police Quarters",
        "buildingNameLocal": "പോലീസ് കോര്‍ട്ടേഴ്സ്",
        "phoneNo": "3/25/8455",
        "phoneDesig": 36,
        "mainPlace": "Kochi",
        "mainPlaceLocal": "കൊച്ചി",
        "registar": [
          {
            "institutionRegistar": "Parvathy K I",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_SUB_INSPECTOR_OF_POLICE"
          }
        ],
        "active": true,
        "address": "Vanitha Police Station,E R G Road,Kompara",
        "addressLocal": "വനിതാ പോലീസ് സ്റ്റേഷന്‍,ഇ ആര്‍ ജി റോഡ്,കോംപാറ",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2407",
        "institutionName": "Fort Kochi Police Station",
        "institutionNamelocal": "ഫോര്‍ട്ട് കൊച്ചി പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2407,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 5,
        "street": "Kamalakadvu",
        "place": "Fort Kochi ",
        "wardId": 1,
        "poId": 22,
        "streetLocal": "കമലക്കടവ്",
        "placeLocal": "ഫോര്‍ട്ട് കൊച്ചി",
        "buildingNo": "NULL",
        "buildingName": "Fort Kochi Police Station",
        "buildingNameLocal": "ഫോര്‍ട്ട് കൊച്ചി പോലീസ് സ്റ്റേഷന്‍",
        "phoneNo": "08/11/64",
        "phoneDesig": 40,
        "mainPlace": "Fort Kochi ",
        "mainPlaceLocal": "ഫോര്‍ട്ട് കൊച്ചി",
        "registar": [
          {
            "institutionRegistar": "Ratheesh Krishnan",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_CIRCLE_INSPECTOR_OF_POLICE"
          }
        ],
        "active": true,
        "address": "Fort Kochi Police Station,Kamalakadvu,Fort Kochi ",
        "addressLocal": "ഫോര്‍ട്ട് കൊച്ചി പോലീസ് സ്റ്റേഷന്‍,കമലക്കടവ്,ഫോര്‍ട്ട് കൊച്ചി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2408",
        "institutionName": "Sneha Bhavan",
        "institutionNamelocal": "സ്നേഹഭവന്‍",
        "instId": 2408,
        "instTypeId": 21,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 6,
        "street": "N H Palluruthy",
        "place": "Palluruthy",
        "wardId": 11,
        "poId": 25,
        "streetLocal": "എന്‍ എച്ച് പള്ളുരുത്തി",
        "placeLocal": "പള്ളുരുത്തി",
        "buildingNo": 252,
        "buildingName": "Snekha Bhavan Palluruthy",
        "buildingNameLocal": "സ്നേഹഭവന്‍ പള്ളുരുത്തി",
        "phoneNo": "05/05/09",
        "phoneDesig": 27,
        "mainPlace": "Palluruthy",
        "mainPlaceLocal": "പള്ളുരുത്തി",
        "registar": [
          {
            "institutionRegistar": "Fr P D Thomas",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_DIRECTOR"
          }
        ],
        "active": true,
        "address": "Sneha Bhavan,N H Palluruthy,Palluruthy",
        "addressLocal": "സ്നേഹഭവന്‍,എന്‍ എച്ച് പള്ളുരുത്തി,പള്ളുരുത്തി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_ORPHANAGE",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2409",
        "institutionName": "Kochi Kasba Police Station",
        "institutionNamelocal": "കൊച്ചി കസ്ബ പോലീസ്സ്റ്റേഷന്‍",
        "instId": 2409,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 7,
        "street": "Palluruthy Nada",
        "place": "Palluruthy ",
        "wardId": 18,
        "poId": 25,
        "streetLocal": "പള്ളുരുത്തിനട",
        "placeLocal": "പള്ളുരുത്തി",
        "buildingNo": "NULL",
        "buildingName": "Kochi Kasba Police Station",
        "buildingNameLocal": "കൊച്ചി കസ്ബ പോലീസ്സ്റ്റേഷന്‍",
        "phoneNo": "08/03/13",
        "phoneDesig": 36,
        "mainPlace": "Palluruthy ",
        "mainPlaceLocal": "പള്ളുരുത്തി",
        "registar": [
          {
            "institutionRegistar": "Ashad",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_SUB_INSPECTOR_OF_POLICE"
          }
        ],
        "active": true,
        "address": "Kochi Kasba Police Station,Palluruthy Nada,Palluruthy ",
        "addressLocal": "കൊച്ചി കസ്ബ പോലീസ്സ്റ്റേഷന്‍,പള്ളുരുത്തിനട,പള്ളുരുത്തി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2410",
        "institutionName": "St. Josephs Waifs Home",
        "institutionNamelocal": "സെന്‍റ് ജോസഫ്സ് വെയ്ഫ്സ് ഹോം",
        "instId": 2410,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 8,
        "street": "Vely",
        "place": "Vely",
        "wardId": 24,
        "poId": 11,
        "streetLocal": "വെളി",
        "placeLocal": "വെളി",
        "buildingNo": 1446,
        "buildingName": "St. Josephs Waifs Home",
        "buildingNameLocal": "സെന്‍റ് ജോസഫ്സ് വെയ്ഫ്സ് ഹോം",
        "phoneNo": "10/14/7996",
        "phoneDesig": 73,
        "mainPlace": "Fort Kochi",
        "mainPlaceLocal": "ഫോര്‍ട്ട് കൊച്ചി",
        "registar": [
          {
            "institutionRegistar": "Sr Mary Peter",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "St. Josephs Waifs Home,Vely,Vely",
        "addressLocal": "സെന്‍റ് ജോസഫ്സ് വെയ്ഫ്സ് ഹോം,വെളി,വെളി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2411",
        "institutionName": "Mattanchery Sub Jail",
        "institutionNamelocal": "മട്ടാഞ്ചേരി സബ് ജയിൽ",
        "instId": 2411,
        "instTypeId": 14,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 9,
        "street": "Moulana Azad Road",
        "place": "Moulana Azad Road",
        "wardId": 6,
        "poId": 11,
        "streetLocal": "മൗലാനാ ആസാദ് റോഡ്",
        "placeLocal": "മൗലാനാ ആസാദ് റോഡ്",
        "buildingNo": 1042,
        "buildingName": "Mattanchery Sub Jail",
        "buildingNameLocal": "മട്ടാഞ്ചേരി സബ് ജെയില്‍",
        "phoneNo": "6/14/7990",
        "phoneDesig": 20,
        "mainPlace": "Mattanchery",
        "mainPlaceLocal": "മട്ടാഞ്ചേരി",
        "registar": [
          {
            "institutionRegistar": "Romeo John",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_SUPERINTENDENT"
          }
        ],
        "active": true,
        "address": "Mattanchery Sub Jail,Moulana Azad Road,Moulana Azad Road",
        "addressLocal": "മട്ടാഞ്ചേരി സബ് ജയിൽ,മൗലാനാ ആസാദ് റോഡ്,മൗലാനാ ആസാദ് റോഡ്",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_JAIL",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2412",
        "institutionName": "City Traffic Polic Station",
        "institutionNamelocal": "സിറ്റി ട്രാഫിക് പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2412,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 10,
        "street": "Old Railway Station Road",
        "place": "Compara",
        "wardId": 40,
        "poId": 5,
        "streetLocal": "ഓള്‍ഡ് റെയില്‍വേ സ്റ്റേഷന്‍ റോഡ്",
        "placeLocal": "കോമ്പാറ",
        "buildingNo": 4393,
        "buildingName": "Police Station Building",
        "buildingNameLocal": "പോലീസ് സ്റ്റേഷന്‍ ബില്‍ഡിംഗ്",
        "phoneNo": "2/21/8455",
        "phoneDesig": 41,
        "mainPlace": "Kochi",
        "mainPlaceLocal": "കൊച്ചി",
        "registar": [
          {
            "institutionRegistar": "V M Sandeep",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_ASSISTANT_SUPERINTENDENT_OF_POLICE"
          }
        ],
        "active": true,
        "address": "City Traffic Polic Station,Old Railway Station Road,Compara",
        "addressLocal": "സിറ്റി ട്രാഫിക് പോലീസ് സ്റ്റേഷന്‍,ഓള്‍ഡ് റെയില്‍വേ സ്റ്റേഷന്‍ റോഡ്,കോമ്പാറ",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2413",
        "institutionName": "Central Police Station",
        "institutionNamelocal": "സെന്‍ട്രല്‍ പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2413,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 11,
        "street": "Old Railway Station Road",
        "place": "Compara",
        "wardId": 40,
        "poId": 5,
        "streetLocal": "ഓള്‍ഡ് റെയില്‍വേ സ്റ്റേഷന്‍ റോഡ്",
        "placeLocal": "കോംപാറ",
        "buildingNo": 0,
        "buildingName": "Central Police Station Building",
        "buildingNameLocal": "സെന്‍ട്രല്‍ പോലീസ് സ്റ്റേഷന്‍ ബില്‍ഡിംഗ്",
        "phoneNo": "11/30/8455",
        "phoneDesig": 40,
        "mainPlace": "Kochi",
        "mainPlaceLocal": "കൊച്ചി",
        "registar": [
          {
            "institutionRegistar": "M Ramesh Kumar",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_CIRCLE_INSPECTOR_OF_POLICE"
          }
        ],
        "active": true,
        "address": "Central Police Station,Old Railway Station Road,Compara",
        "addressLocal": "സെന്‍ട്രല്‍ പോലീസ് സ്റ്റേഷന്‍,ഓള്‍ഡ് റെയില്‍വേ സ്റ്റേഷന്‍ റോഡ്,കോംപാറ",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2414",
        "institutionName": "Ernakulam Town North Police Station",
        "institutionNamelocal": "എറണുകുളം ഠൗണ്‍ നോര്‍ത്ത് പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2414,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 12,
        "street": "Chittoor Road",
        "place": "Trikkanar Vattom",
        "wardId": 40,
        "poId": 5,
        "streetLocal": "ചിറ്റൂര്‍ റോഡ്",
        "placeLocal": "ത്രികണാര്‍ വട്ടം",
        "buildingNo": 0,
        "buildingName": "Ernakulam Town North Police Station",
        "buildingNameLocal": "എറണുകുളം ഠൗണ്‍ നോര്‍ത്ത് പോലീസ് സ്റ്റേഷന്‍",
        "phoneNo": "05/11/44",
        "phoneDesig": 36,
        "mainPlace": "Ernakulam North",
        "mainPlaceLocal": "എറണുകുളം നോര്‍ത്ത്",
        "registar": [
          {
            "institutionRegistar": "Abdul Raheem",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_SUB_INSPECTOR_OF_POLICE"
          }
        ],
        "active": true,
        "address": "Ernakulam Town North Police Station,Chittoor Road,Trikkanar Vattom",
        "addressLocal": "എറണുകുളം ഠൗണ്‍ നോര്‍ത്ത് പോലീസ് സ്റ്റേഷന്‍,ചിറ്റൂര്‍ റോഡ്,ത്രികണാര്‍ വട്ടം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2415",
        "institutionName": "Palarivattom Police Station",
        "institutionNamelocal": "പാലാരിവട്ടം പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2415,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 13,
        "street": "Palarivattom",
        "place": "Palarivattom",
        "wardId": 50,
        "poId": 18,
        "streetLocal": "പാലാരിവട്ടം",
        "placeLocal": "പാലാരിവട്ടം",
        "buildingNo": 0,
        "buildingName": "Palarivattom Police Station",
        "buildingNameLocal": "പാലാരിവട്ടം പോലീസ് സ്റ്റേഷന്‍",
        "phoneNo": "6/18/8290",
        "phoneDesig": 36,
        "mainPlace": "Palarivattom",
        "mainPlaceLocal": "പാലാരിവട്ടം",
        "registar": [
          {
            "institutionRegistar": "Jose M M ",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_SUB_INSPECTOR_OF_POLICE"
          }
        ],
        "active": true,
        "address": "Palarivattom Police Station,Palarivattom,Palarivattom",
        "addressLocal": "പാലാരിവട്ടം പോലീസ് സ്റ്റേഷന്‍,പാലാരിവട്ടം,പാലാരിവട്ടം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2416",
        "institutionName": "Ernakulam South Police Station",
        "institutionNamelocal": "എറണാകുളം സൗത്ത് പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2416,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 14,
        "street": "M G Road",
        "place": "Thevara Junction",
        "wardId": 26,
        "poId": 16,
        "streetLocal": "എം ജി റോഡ്",
        "placeLocal": "തേവര ജംഗ്ഷന്‍",
        "buildingNo": 21,
        "buildingName": "Ernakulam South Police Station",
        "buildingNameLocal": "എറണാകുളം സൗത്ത് പോലീസ് സ്റ്റേഷന്‍",
        "phoneNo": "09/05/59",
        "phoneDesig": 36,
        "mainPlace": "Kochi",
        "mainPlaceLocal": "കൊച്ചി",
        "registar": [
          {
            "institutionRegistar": "Ajayanath",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_SUB_INSPECTOR_OF_POLICE"
          }
        ],
        "active": true,
        "address": "Ernakulam South Police Station,M G Road,Thevara Junction",
        "addressLocal": "എറണാകുളം സൗത്ത് പോലീസ് സ്റ്റേഷന്‍,എം ജി റോഡ്,തേവര ജംഗ്ഷന്‍",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2417",
        "institutionName": "Thoppumpady Police Station",
        "institutionNamelocal": "തോപ്പുംപടി പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2417,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 15,
        "street": "Thoppumpady",
        "place": "Thoppumpady",
        "wardId": 1,
        "poId": 21,
        "streetLocal": "തോപ്പുംപടി",
        "placeLocal": "തോപ്പുംപടി",
        "buildingNo": 247,
        "buildingName": "Cochin Port Building",
        "buildingNameLocal": "കൊച്ചിന്‍ പോര്‍ട്ട് ബില്‍ഡിംഗ്",
        "phoneNo": "03/11/89",
        "phoneDesig": 36,
        "mainPlace": "Thoppumpady",
        "mainPlaceLocal": "തോപ്പുംപടി",
        "registar": [
          {
            "institutionRegistar": "P P Shams",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_SUB_INSPECTOR_OF_POLICE"
          }
        ],
        "active": true,
        "address": "Thoppumpady Police Station,Thoppumpady,Thoppumpady",
        "addressLocal": "തോപ്പുംപടി പോലീസ് സ്റ്റേഷന്‍,തോപ്പുംപടി,തോപ്പുംപടി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2418",
        "institutionName": "Edappally Trafic Policestation",
        "institutionNamelocal": "ഇടപ്പള്ളി ട്രാഫിക് പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2418,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 16,
        "street": "Market Road",
        "place": "Edappally",
        "wardId": 33,
        "poId": 10,
        "streetLocal": "മാര്‍ക്കറ്റ് റോഡ്",
        "placeLocal": "ഇടപ്പള്ളി",
        "buildingNo": "NULL",
        "buildingName": "Edappally Trafic Policestation",
        "buildingNameLocal": "ഇടപ്പള്ളി ട്രാഫിക് പോലീസ് സ്റ്റേഷന്‍",
        "phoneNo": "NULL",
        "phoneDesig": 36,
        "mainPlace": "Edappally",
        "mainPlaceLocal": "ഇടപ്പള്ളി",
        "registar": [
          {
            "institutionRegistar": "Mohandas T D",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_SUB_INSPECTOR_OF_POLICE"
          }
        ],
        "active": true,
        "address": "Edappally Trafic Policestation,Market Road,Edappally",
        "addressLocal": "ഇടപ്പള്ളി ട്രാഫിക് പോലീസ് സ്റ്റേഷന്‍,മാര്‍ക്കറ്റ് റോഡ്,ഇടപ്പള്ളി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2419",
        "institutionName": "Missionaries of Charity",
        "institutionNamelocal": "മിഷിനറീസ് ഓഫ് ചാരിറ്റി",
        "instId": 2419,
        "instTypeId": 42,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 17,
        "street": null,
        "place": "Eranakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Missionaries of Charity",
        "buildingNameLocal": "മിഷിനറീസ് ഓഫ് ചാരിറ്റി",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Eranakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Alphonsite",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Missionaries of Charity,Eranakulam",
        "addressLocal": "മിഷിനറീസ് ഓഫ് ചാരിറ്റി,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_DESTITUTE_HOME",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2420",
        "institutionName": "Nirmala Sisubhavan",
        "institutionNamelocal": "നിര്‍മ്മല ശിശുഭവന്‍",
        "instId": 2420,
        "instTypeId": 21,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 18,
        "street": null,
        "place": "Eranakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Nirmala Sisubhavan",
        "buildingNameLocal": "നിര്‍മ്മല ശിശുഭവന്‍",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Eranakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Angelette M C",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Nirmala Sisubhavan,Eranakulam",
        "addressLocal": "നിര്‍മ്മല ശിശുഭവന്‍,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_ORPHANAGE",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2421",
        "institutionName": "Yatheem Khana",
        "institutionNamelocal": "യത്തീം ഖാന",
        "instId": 2421,
        "instTypeId": 21,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 19,
        "street": "Pulleppadi Arangath Cross Road",
        "place": "Eranakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": "പുല്ലേപ്പടി അരങ്ങത്ത് ക്രോസ് റോഡ്",
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Yatheem Khana",
        "buildingNameLocal": "യത്തീം ഖാന",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Eranakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": null,
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Yatheem Khana,Pulleppadi Arangath Cross Road,Eranakulam",
        "addressLocal": "യത്തീം ഖാന,പുല്ലേപ്പടി അരങ്ങത്ത് ക്രോസ് റോഡ്,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_ORPHANAGE",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2422",
        "institutionName": "Sainika Asramam",
        "institutionNamelocal": "സൈനിക ആശ്രമം",
        "instId": 2422,
        "instTypeId": 41,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 20,
        "street": "Palarivattom",
        "place": "Kochi",
        "wardId": 1,
        "poId": 1,
        "streetLocal": "പാലാരിവട്ടം",
        "placeLocal": "കൊച്ചി",
        "buildingNo": "NULL",
        "buildingName": "Sainika Asramam",
        "buildingNameLocal": "സൈനിക ആശ്രമം",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Eranakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": null,
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Sainika Asramam,Palarivattom,Kochi",
        "addressLocal": "സൈനിക ആശ്രമം,പാലാരിവട്ടം,കൊച്ചി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2423",
        "institutionName": "Karunalayam",
        "institutionNamelocal": "കരുണാലയം",
        "instId": 2423,
        "instTypeId": 20,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 21,
        "street": "Chunanganveli",
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": "ചുണങ്ങംവേലി",
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Karunalayam",
        "buildingNameLocal": "കരുണാലയം",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": null,
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Karunalayam,Chunanganveli,Ernakulam",
        "addressLocal": "കരുണാലയം,ചുണങ്ങംവേലി,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_OLD_AGE_HOME",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2424",
        "institutionName": "Sree Narayana Vidhyarthi Sadanam",
        "institutionNamelocal": "ശ്രീനാരായണ വിദ്യാര്‍ത്ഥി സദനം",
        "instId": 2424,
        "instTypeId": 13,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 22,
        "street": "Ayyappan Kovil Road",
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": "അയ്യപ്പന്‍ കോവില്‍ റോഡ്",
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Sree Narayana Vidhyarthi Sadanam",
        "buildingNameLocal": "ശ്രീനാരായണ വിദ്യാര്‍ത്ഥി സദനം",
        "phoneNo": "NULL",
        "phoneDesig": 69,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sumithra Rammohan",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_PERSON_(I/C)"
          }
        ],
        "active": true,
        "address": "Sree Narayana Vidhyarthi Sadanam,Ayyappan Kovil Road,Ernakulam",
        "addressLocal": "ശ്രീനാരായണ വിദ്യാര്‍ത്ഥി സദനം,അയ്യപ്പന്‍ കോവില്‍ റോഡ്,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_HOSTEL",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2425",
        "institutionName": "Mother Theresa Convent Sisubhavan",
        "institutionNamelocal": "മദര്‍ തെരേസ കോണ്‍വെന്‍റ് ശിശുഭവന്‍",
        "instId": 2425,
        "instTypeId": 40,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 23,
        "street": null,
        "place": "Eranakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Mother Theresa Convent Sisubhavan",
        "buildingNameLocal": "മദര്‍ തെരേസ കോണ്‍വെന്‍റ് ശിശുഭവന്‍",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Eranakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Ashrita",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Mother Theresa Convent Sisubhavan,Eranakulam",
        "addressLocal": "മദര്‍ തെരേസ കോണ്‍വെന്‍റ് ശിശുഭവന്‍,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2426",
        "institutionName": "House of Providence ",
        "institutionNamelocal": "ഹൗസ് ഓഫ് പ്രൊവിഡന്‍സ്",
        "instId": 2426,
        "instTypeId": 42,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 24,
        "street": null,
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "House of Providence",
        "buildingNameLocal": "ഹൗസ് ഓഫ് പ്രൊവിഡന്‍സ്",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Helera",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "House of Providence ,Ernakulam",
        "addressLocal": "ഹൗസ് ഓഫ് പ്രൊവിഡന്‍സ്,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_DESTITUTE_HOME",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2427",
        "institutionName": "Home for the Destitude",
        "institutionNamelocal": "ഹോം ഫോര്‍ ദെ ഡെസ്റ്റിറ്റ്യൂഡ്",
        "instId": 2427,
        "instTypeId": 42,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 25,
        "street": "Perumanur",
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": "പെരുമണൂര്‍",
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Home for the Destitude",
        "buildingNameLocal": "ഹോം ഫോര്‍ ദെ ഡെസ്റ്റിറ്റ്യൂഡ്",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Jolanda",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Home for the Destitude,Perumanur,Ernakulam",
        "addressLocal": "ഹോം ഫോര്‍ ദെ ഡെസ്റ്റിറ്റ്യൂഡ്,പെരുമണൂര്‍,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_DESTITUTE_HOME",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2428",
        "institutionName": "Vimalalayam",
        "institutionNamelocal": "വിമലാലയം",
        "instId": 2428,
        "instTypeId": 42,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 26,
        "street": null,
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Vimalalayam",
        "buildingNameLocal": "വിമലാലയം",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Mary John",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Vimalalayam,Ernakulam",
        "addressLocal": "വിമലാലയം,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_DESTITUTE_HOME",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2429",
        "institutionName": "Adoration Convent",
        "institutionNamelocal": "അഡോറേഷന്‍ കോണ്‍വെന്‍റ്",
        "instId": 2429,
        "instTypeId": 40,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 27,
        "street": null,
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Adoration Convent",
        "buildingNameLocal": "അഡോറേഷന്‍ കോണ്‍വെന്‍റ്",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Tessy Puthussery",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Adoration Convent,..,Ernakulam",
        "addressLocal": "അഡോറേഷന്‍ കോണ്‍വെന്‍റ്,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2430",
        "institutionName": "St Theresas Mercy Home",
        "institutionNamelocal": "സെന്‍റ് തെരേസാസ് മേഴ്സി ഹോം",
        "instId": 2430,
        "instTypeId": 9,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 28,
        "street": null,
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "St Theresas Mercy Home",
        "buildingNameLocal": "സെന്‍റ് തെരേസാസ് മേഴ്സി ഹോം",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Archana",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "St Theresas Mercy Home,Ernakulam",
        "addressLocal": "സെന്‍റ് തെരേസാസ് മേഴ്സി ഹോം,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_DESTITUTE_HOME",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2431",
        "institutionName": "Gandhimandiram, Navajeevan",
        "institutionNamelocal": "ഗാന്ധിമന്ദിരം, നവജീവന്‍",
        "instId": 2431,
        "instTypeId": 41,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 29,
        "street": null,
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Gandhimandiram, Navajeevan",
        "buildingNameLocal": "ഗാന്ധിമന്ദിരം, നവജീവന്‍",
        "phoneNo": "NULL",
        "phoneDesig": 69,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "G Gopal",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_PERSON_(I/C)"
          }
        ],
        "active": true,
        "address": "Gandhimandiram, Navajeevan,Ernakulam",
        "addressLocal": "ഗാന്ധിമന്ദിരം, നവജീവന്‍,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2432",
        "institutionName": "Govt Old Age Home",
        "institutionNamelocal": "ഗവ. ഓള്‍ഡ് ഏജ് ഹോം",
        "instId": 2432,
        "instTypeId": 20,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 30,
        "street": "Thevara",
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": "തേവര",
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Govt Old Age Home",
        "buildingNameLocal": "ഗവ. ഓള്‍ഡ് ഏജ് ഹോം",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "്എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": null,
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Govt Old Age Home,Thevara,Ernakulam",
        "addressLocal": "ഗവ. ഓള്‍ഡ് ഏജ് ഹോം,തേവര,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_OLD_AGE_HOME",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2433",
        "institutionName": "St Francis Assissi Cathedral",
        "institutionNamelocal": "സെന്‍റ് ഫ്രാന്‍സിസ് അസ്സിസ്സി കത്തീഡ്രല്‍",
        "instId": 2433,
        "instTypeId": 40,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 31,
        "street": null,
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "St Francis Assissi Cathedral",
        "buildingNameLocal": "സെന്‍റ് ഫ്രാന്‍സിസ് അസ്സിസ്സി കത്തീഡ്രല്‍",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": null,
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "St Francis Assissi Cathedral,..,Ernakulam",
        "addressLocal": "സെന്‍റ് ഫ്രാന്‍സിസ് അസ്സിസ്സി കത്തീഡ്രല്‍,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2434",
        "institutionName": "St James Convent",
        "institutionNamelocal": "സെന്‍റ് ജെയിംസ് കോണ്‍വെന്‍റ്",
        "instId": 2434,
        "instTypeId": 40,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 32,
        "street": "Poonithura",
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": "പൂണിത്തുറ",
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "St James Convent",
        "buildingNameLocal": "സെന്‍റ് ജെയിംസ് കോണ്‍വെന്‍റ്",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": null,
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "St James Convent,Poonithura,Ernakulam",
        "addressLocal": "സെന്‍റ് ജെയിംസ് കോണ്‍വെന്‍റ്,പൂണിത്തുറ,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2435",
        "institutionName": "Agricultural Research and Service Centre",
        "institutionNamelocal": "അഗ്രികള്‍ച്ചറല്‍ റിസേര്‍ച്ച് ആന്‍റ് സര്‍വീസ് സെന്‍റര്‍",
        "instId": 2435,
        "instTypeId": 10,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 33,
        "street": null,
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Agricultural Research and Service Centre",
        "buildingNameLocal": "അഗ്രികള്‍ച്ചറല്‍ റിസേര്‍ച്ച് ആന്‍റ് സര്‍വീസ് സെന്‍റര്‍",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": null,
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Agricultural Research and Service Centre,Ernakulam",
        "addressLocal": "അഗ്രികള്‍ച്ചറല്‍ റിസേര്‍ച്ച് ആന്‍റ് സര്‍വീസ് സെന്‍റര്‍,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_EDUCATIONAL_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2436",
        "institutionName": "Mount Carmel Orphanage",
        "institutionNamelocal": "മൗണ്ട് കാര്‍മല്‍ ഓര്‍ഫനേജ്",
        "instId": 2436,
        "instTypeId": 21,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 34,
        "street": "Chathiath",
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": "ചാത്തിയത്ത്",
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Mount Carmel Orphanage",
        "buildingNameLocal": "മൗണ്ട് കാര്‍മല്‍ ഓര്‍ഫനേജ്",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Earnets",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Mount Carmel Orphanage,Chathiath,Ernakulam",
        "addressLocal": "മൗണ്ട് കാര്‍മല്‍ ഓര്‍ഫനേജ്,ചാത്തിയത്ത്,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_ORPHANAGE",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2437",
        "institutionName": "Ernakulam Sathya Sai Samathi",
        "institutionNamelocal": "എറണാകുളം സത്യ സായി സമതി",
        "instId": 2437,
        "instTypeId": 42,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 35,
        "street": null,
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Ernakulam Sathya Sai Samathi",
        "buildingNameLocal": "എറണാകുളം സത്യ സായി സമതി",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": null,
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Ernakulam Sathya Sai Samathi,Ernakulam",
        "addressLocal": "എറണാകുളം സത്യ സായി സമതി,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_DESTITUTE_HOME",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2438",
        "institutionName": "St Theresas Convent ",
        "institutionNamelocal": "സെന്‍റ് തെരേസാസ് കോണ്‍വെന്‍റ്",
        "instId": 2438,
        "instTypeId": 40,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 36,
        "street": "Ernakulam",
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": "എറണാകുളം",
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "St Theresas Convent ",
        "buildingNameLocal": "സെന്‍റ് തെരേസാസ് കോണ്‍വെന്‍റ്",
        "phoneNo": "NULL",
        "phoneDesig": 69,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Ashrita",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_PERSON_(I/C)"
          }
        ],
        "active": true,
        "address": "St Theresas Convent ,Ernakulam,Ernakulam",
        "addressLocal": "സെന്‍റ് തെരേസാസ് കോണ്‍വെന്‍റ്,എറണാകുളം,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2439",
        "institutionName": "Holy Family Monostry",
        "institutionNamelocal": "ഹോളി ഫാമിലി മോണോസ്ട്രി",
        "instId": 2439,
        "instTypeId": 41,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 37,
        "street": null,
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Holy Family Monostry",
        "buildingNameLocal": "ഹോളി ഫാമിലി മോണോസ്ട്രി",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": null,
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Holy Family Monostry,Ernakulam",
        "addressLocal": "ഹോളി ഫാമിലി മോണോസ്ട്രി,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2440",
        "institutionName": "Abalasramam Girls Industrial School ",
        "institutionNamelocal": "അബലാശ്രമം ഗേള്‍സ് ഇന്‍ഡസ്ട്രിയല്‍ സ്കൂള്‍",
        "instId": 2440,
        "instTypeId": 10,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 38,
        "street": null,
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Abalasramam Girls Industrial School ",
        "buildingNameLocal": "അബലാശ്രമം ഗേള്‍സ് ഇന്‍ഡസ്ട്രിയല്‍ സ്കൂള്‍",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": null,
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Abalasramam Girls Industrial School ,Ernakulam",
        "addressLocal": "അബലാശ്രമം ഗേള്‍സ് ഇന്‍ഡസ്ട്രിയല്‍ സ്കൂള്‍,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_EDUCATIONAL_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2441",
        "institutionName": "Anugraha Convent",
        "institutionNamelocal": "അനുഗ്രഹ കോണ്‍വെന്‍റ്",
        "instId": 2441,
        "instTypeId": 40,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 39,
        "street": null,
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": "എറണാകുളം",
        "buildingNo": "NULL",
        "buildingName": "Anugraha Convent",
        "buildingNameLocal": "അനുഗ്രഹ കോണ്‍വെന്‍റ്",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Ashritha",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Anugraha Convent,Ernakulam",
        "addressLocal": "അനുഗ്രഹ കോണ്‍വെന്‍റ്,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2442",
        "institutionName": "Relief Settlement",
        "institutionNamelocal": "റിലീഫ് സെറ്റില്‍മെന്‍റ്",
        "instId": 2442,
        "instTypeId": 42,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 40,
        "street": null,
        "place": null,
        "wardId": 1,
        "poId": 1,
        "streetLocal": null,
        "placeLocal": null,
        "buildingNo": "NULL",
        "buildingName": "Relief Settlement",
        "buildingNameLocal": "റിലീഫ് സെറ്റില്‍മെന്‍റ്",
        "phoneNo": "NULL",
        "phoneDesig": 21,
        "mainPlace": ".",
        "mainPlaceLocal": ".",
        "registar": [
          {
            "institutionRegistar": "Mathew M C",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_MANAGER"
          }
        ],
        "active": true,
        "address": "Relief Settlement,.",
        "addressLocal": "റിലീഫ് സെറ്റില്‍മെന്‍റ്,.",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_DESTITUTE_HOME",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2443",
        "institutionName": "Central Excise Office",
        "institutionNamelocal": "സെന്‍ട്രല്‍ എക്സൈസ് ആഫീസ്",
        "instId": 2443,
        "instTypeId": 19,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 41,
        "street": "Thavakandom Centre",
        "place": "cochi",
        "wardId": 1,
        "poId": 28,
        "streetLocal": "താവകാണ്ടം സെന്‍റര്‍",
        "placeLocal": "കൊച്ചി",
        "buildingNo": "NULL",
        "buildingName": "Central Excise Office",
        "buildingNameLocal": "സെന്‍ട്രല്‍ എക്സൈസ് ആഫീസ്",
        "phoneNo": "NULL",
        "phoneDesig": 20,
        "mainPlace": "cochi",
        "mainPlaceLocal": "കൊച്ചി",
        "registar": [
          {
            "institutionRegistar": "Radhakrishnan menon M K",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_SUPERINTENDENT"
          }
        ],
        "active": true,
        "address": "Central Excise Office,Thavakandom Centre,cochi",
        "addressLocal": "സെന്‍ട്രല്‍ എക്സൈസ് ആഫീസ്,താവകാണ്ടം സെന്‍റര്‍,കൊച്ചി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_OTHER_INSTITUTIONS_SPECIFY",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2444",
        "institutionName": "St Francis Xaviers Convent",
        "institutionNamelocal": "സെന്‍റ് ഫ്രാന്‍സിസ് കോണ്‍വെന്‍റ്",
        "instId": 2444,
        "instTypeId": 40,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 42,
        "street": "Kaloor",
        "place": "cochi",
        "wardId": 1,
        "poId": 1,
        "streetLocal": "കലൂര്‍",
        "placeLocal": "കൊച്ചി",
        "buildingNo": "NULL",
        "buildingName": "St Francis Xaviers Convent",
        "buildingNameLocal": "സെന്‍റ് ഫ്രാന്‍സിസ് കോണ്‍വെന്‍റ്",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Eranakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Ansalema",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "St Francis Xaviers Convent,Kaloor,cochi",
        "addressLocal": "സെന്‍റ് ഫ്രാന്‍സിസ് കോണ്‍വെന്‍റ്,കലൂര്‍,കൊച്ചി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2445",
        "institutionName": "St. Maegy Convent",
        "institutionNamelocal": "സെന്‍റ് മാഗി കോണ്‍വെന്‍റ്",
        "instId": 2445,
        "instTypeId": 40,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 43,
        "street": "Kaloor",
        "place": "cochin",
        "wardId": 1,
        "poId": 1,
        "streetLocal": "കലൂര്‍",
        "placeLocal": "കൊച്ചി",
        "buildingNo": 897,
        "buildingName": "St. Maegy Convent",
        "buildingNameLocal": "സെന്‍റ് മാഗി കോണ്‍വെന്‍റ്",
        "phoneNo": "NULL",
        "phoneDesig": 35,
        "mainPlace": "Eranakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr christeena",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OFFICER_IN_CHARGE"
          }
        ],
        "active": true,
        "address": "St. Maegy Convent,Kaloor,cochin",
        "addressLocal": "സെന്‍റ് മാഗി കോണ്‍വെന്‍റ്,കലൂര്‍,കൊച്ചി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2446",
        "institutionName": "Wiilington Island PoliceStation",
        "institutionNamelocal": "വില്ലിംഗ്ടണ്‍ ഐലന്‍റ് പോലീസ് സ്റ്റേഷന്‍",
        "instId": 2446,
        "instTypeId": 29,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 44,
        "street": "Wiilington Island",
        "place": "Cochin",
        "wardId": 1,
        "poId": 22,
        "streetLocal": "വില്ലിംഗ്ടണ്‍ ഐലന്‍റ",
        "placeLocal": "കൊച്ചിന്‍",
        "buildingNo": "NULL",
        "buildingName": "Wiilington Island PoliceStation",
        "buildingNameLocal": "വില്ലിംഗ്ടണ്‍ ഐലന്‍റ് പോലീസ് സ്റ്റേഷന്‍",
        "phoneNo": "NULL",
        "phoneDesig": 38,
        "mainPlace": "Eranakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Balakrishnan P P",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_HEAD_CONSTABLE"
          }
        ],
        "active": true,
        "address": "Wiilington Island PoliceStation,Wiilington Island,Cochin",
        "addressLocal": "വില്ലിംഗ്ടണ്‍ ഐലന്‍റ് പോലീസ് സ്റ്റേഷന്‍,വില്ലിംഗ്ടണ്‍ ഐലന്‍റ,കൊച്ചിന്‍",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_POLICE_STATION",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2447",
        "institutionName": "St Marys Convent ",
        "institutionNamelocal": "സെന്‍റ് മേരീസ് കോണ്‍വെന്‍റ്",
        "instId": 2447,
        "instTypeId": 40,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 45,
        "street": "Kaloor",
        "place": "Cochi",
        "wardId": 1,
        "poId": 22,
        "streetLocal": "കലൂര്‍",
        "placeLocal": "കൊച്ചി",
        "buildingNo": "NULL",
        "buildingName": ".",
        "buildingNameLocal": ".",
        "phoneNo": "NULL",
        "phoneDesig": 35,
        "mainPlace": "Eranakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Sr Ascanse",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OFFICER_IN_CHARGE"
          }
        ],
        "active": true,
        "address": "St Marys Convent ,Kaloor,Cochi",
        "addressLocal": "സെന്‍റ് മേരീസ് കോണ്‍വെന്‍റ്,കലൂര്‍,കൊച്ചി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2448",
        "institutionName": "Taj Lodge",
        "institutionNamelocal": "താജ് ലോഡ്ജ്",
        "instId": 2448,
        "instTypeId": 15,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 46,
        "street": null,
        "place": "Cochi",
        "wardId": 1,
        "poId": 22,
        "streetLocal": null,
        "placeLocal": "കൊച്ചി",
        "buildingNo": "NULL",
        "buildingName": "Taj Lodge",
        "buildingNameLocal": "താജ് ലോഡ്ജ്",
        "phoneNo": "NULL",
        "phoneDesig": 24,
        "mainPlace": "Eranakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": "Balakrishnan K A",
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_MANAGING_PARTNER"
          }
        ],
        "active": true,
        "address": "Taj Lodge,Cochi",
        "addressLocal": "താജ് ലോഡ്ജ്,കൊച്ചി",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_LODGE/BOARDING_HOUSE",
        "migrationKochiCode": null
      },
      {
        "code": "INSTITUTION_2449",
        "institutionName": "Sree Bhuvanendra Prasidha Vridhaisram",
        "institutionNamelocal": "ശ്രീ ബുവനേന്ദ്ര പ്രസിദ്ധ വൃദ്ധാശ്രമം",
        "instId": 2449,
        "instTypeId": 41,
        "stateId": 32,
        "distId": 7,
        "lbId": 169,
        "slNo": 47,
        "street": "Menaga",
        "place": "Ernakulam",
        "wardId": 1,
        "poId": 28,
        "streetLocal": "മേനക",
        "placeLocal": "എറണാകുളം",
        "buildingNo": 324,
        "buildingName": "Sree Bhuvanendra Prasidha Vridhaisram",
        "buildingNameLocal": "ശ്രീ ബുവനേന്ദ്ര പ്രസിദ്ധ വൃദ്ധാശ്രമം",
        "phoneNo": "NULL",
        "phoneDesig": 73,
        "mainPlace": "Ernakulam",
        "mainPlaceLocal": "എറണാകുളം",
        "registar": [
          {
            "institutionRegistar": null,
            "registrationAadhaar": null,
            "registrationMobile": null,
            "registarDesig": "DESIGNATION_OTHERS"
          }
        ],
        "active": true,
        "address": "Sree Bhuvanendra Prasidha Vridhaisram,Menaga,Ernakulam",
        "addressLocal": "ശ്രീ ബുവനേന്ദ്ര പ്രസിദ്ധ വൃദ്ധാശ്രമം,മേനക,എറണാകുളം",
        "lbCode": "kl.cochin",
        "placeofEventCodeNew": "INST_TYPE_RELIGIOUS_INSTITUTIONS",
        "migrationKochiCode": null
      }
    ]
  }